name: chocolatine

on:
  push:
    branches:
      - '**'
      - '!ga-ignore-*'
  pull_request:
    branches:
      - '**'
      - '!ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:UlysseZumbrunn/ChocolatineMiRRORTEST.git"
  EXECUTABLES: ${{ secrets.EXECUTABLES }}

jobs:
#   check_coding_style:
#     runs-on: ubuntu-latest
#     container: ghcr.io/epitech/coding-style-checker:latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Run coding style checker
#         run: check.sh $(pwd) $(pwd)
#       - name: Display error annotations
#         if: failure()
#         uses: actions/checkout@v3
#         with:
#           filename: 'output.log'
#       - name: Fail job on coding style errors
#         if: failure()
#         run: exit 1

#   check_program_compilation:
#     env:
#       EXECUTABLES: ${{ secrets.EXECUTBALES }}
#     runs-on: ubuntu-latest
#     container: epitechcontent/epitest-docker:latest
#     timeout-minutes: 2
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Make
#         run: |
#           make
#           make clean
#       - name: Verify executables
#         run: |
#           for executable in $(echo "$EXECUTABLES" | sed "s/,/ /g"); do
#             if [ ! -x "$executable" ]; then
#               echo "Executable $executable not found or not executable"
#               exit 1
#             fi
#           done

#   run_tests:
#     runs-on: ubuntu-latest
#     container: epitechcontent/epitest-docker
#     timeout-minutes: 2
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Make tests
#         run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    # needs: [check_program_compilation, run_tests]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          mirror_url: git@github.com:UlysseZumbrunn/ChocolatineMiRRORTEST.git
          private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
